version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 99
  labels:
  - maintenance
  - dependencies
  ignore:
  - dependency-name: Django
    versions:
    - ">=3.0"
  - dependency-name: importlib-metadata
    versions:
    - 3.10.0
    - 3.4.0
    - 3.7.0
    - 3.7.2
    - 3.7.3
    - 3.9.0
    - 4.0.0
  - dependency-name: django-extensions
    versions:
    - 3.1.0
    - 3.1.1
    - 3.1.2
  - dependency-name: flake8
    versions:
    - 3.8.4
    - 3.9.0
  - dependency-name: pyflakes
    versions:
    - 2.2.0
    - 2.3.0
  - dependency-name: pillow
    versions:
    - 8.1.0
    - 8.1.2
  - dependency-name: sentry-sdk
    versions:
    - 0.19.5
    - 0.20.1
    - 0.20.3
  - dependency-name: josepy
    versions:
    - 1.5.0
    - 1.6.0
    - 1.7.0
  - dependency-name: django
    versions:
    - 2.2.17
    - 2.2.18
  - dependency-name: pytest
    versions:
    - 6.2.1
    - 6.2.2
  - dependency-name: urllib3
    versions:
    - 1.26.2
    - 1.26.3
  - dependency-name: django-cache-url
    versions:
    - 3.1.2
    - 3.2.2
  - dependency-name: newrelic
    versions:
    - 6.0.1.155
  - dependency-name: deprecated
    versions:
    - 1.2.11
  - dependency-name: pytz
    versions:
    - "2020.5"
  - dependency-name: pygithub
    versions:
    - 1.54.1
  - dependency-name: packaging
    versions:
    - "20.8"
  - dependency-name: cffi
    versions:
    - 1.14.4
  - dependency-name: more-itertools
    versions:
    - 8.6.0
  - dependency-name: markdown
    versions:
    - 3.3.3
  - dependency-name: pytest-django
    versions:
    - 4.1.0
  - dependency-name: zipp
    versions:
    - 3.4.0
  - dependency-name: configparser
    versions:
    - 5.0.1
  - dependency-name: jinja2
    versions:
    - 2.11.2
  - dependency-name: pycodestyle
    versions:
    - 2.6.0
  - dependency-name: gunicorn
    versions:
    - 20.0.4
