# Global excludes, override per repo below if different excludes required.
exclude: >
  (?x)^(
    root_files
    | jenkins
  )
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.9
    hooks:
      - id: ruff
      - id: ruff-format