# Global excludes, override per repo below if different excludes required.
exclude: >
  (?x)^(
    root_files
    | jenkins
  )
repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.11
    hooks:
      - id: ruff
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3
