
[tool.ruff]
# Set what ruff should check for.
# See https://beta.ruff.rs/docs/rules/ for a list of rules.
lint.select = [
    # TODO: Enable flake8-builtin and fix errors to fix variable name shadowing errors.
    # "A", # flake8-builtin errors.
    # TODO: Enable bugbear and fix errors.
    # "B", # bugbear errors
    "DJ", # flake8-django errors.
    "E", # pycodestyle errors
    "F", # pyflakes errors
    "I", # import sorting
    "Q", # flake8-quotes errors
    "W", # pycodestyle warnings
]
line-length = 150
target-version = 'py312'
extend-exclude = ["__pycache__", "docs", "assets", "static", "bedrock/externalfiles/files_cache"]

[tool.ruff.lint.per-file-ignores]
"nucleus/settings.py" = ["F405"]

[tool.ruff.lint.isort]
known-first-party = ["nucleus", "base", "rna", "lib", "pages"]
section-order = ["future", "standard-library", "django", "third-party", "first-party", "local-folder"]
combine-as-imports = true

[tool.ruff.lint.isort.sections]
django = ["django"]
