# Generated by Django 3.2.23 on 2023-11-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rna", "0005_auto_20211006_1201"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="progressive_rollout",
            field=models.BooleanField(default=False),
        ),
    ]
