# Generated by Django 3.2.23 on 2023-11-23 13:24

from django.db import migrations, models

import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("rna", "0007_release_reviewed_by_release_manager"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(blank=True, db_index=True, editable=False)),
                ("name", models.CharField(max_length=128)),
                ("code", models.CharField(help_text="3166-1-alpha-2 code", max_length=2)),
            ],
        ),
        migrations.AddConstraint(
            model_name="country",
            constraint=models.UniqueConstraint(fields=("name", "code"), name="unique_country_name_for_code"),
        ),
    ]
