# Generated by Django 3.2.23 on 2023-11-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rna", "0009_data_bootstrap_countries_and_codes"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="relevant_countries",
            field=models.ManyToManyField(blank=True, help_text="Countries, if any, to which this Note only applies", to="rna.Country"),
        ),
    ]
