# Generated by Django 4.2.24 on 2026-03-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rna", "0011_alter_country_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="tag",
            field=models.CharField(
                blank=True,
                choices=[
                    ("New", "New"),
                    ("Changed", "Changed"),
                    ("HTML5", "HTML5"),
                    ("Feature", "Feature"),
                    ("Language", "Language"),
                    ("Developer", "Developer"),
                    ("Enterprise", "Enterprise"),
                    ("Fixed", "Fixed"),
                    ("Community", "Community"),
                    ("Labs", "Labs"),
                ],
                max_length=255,
            ),
        ),
    ]
