# Generated by Django 4.2.30 on 2026-08-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rna", "0012_alter_note_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="release",
            name="product",
            field=models.CharField(
                choices=[
                    ("Firefox", "Firefox"),
                    ("Firefox Enterprise", "Firefox Enterprise"),
                    ("Firefox Extended Support Release", "Firefox Extended Support Release"),
                    ("Firefox for Android", "Firefox for Android"),
                    ("Firefox for iOS", "Firefox for iOS"),
                    ("Thunderbird", "Thunderbird"),
                ],
                max_length=255,
            ),
        ),
    ]
